# tensor (张量)

## 1.创建张量

In [2]:
import torch

In [2]:
# 创建一个5×3的矩阵，
print(torch.empty(5, 3, dtype=torch.float32))

# 创建一个随机矩阵0-1
print(torch.rand(4, 4))

# 创建一个以0填充的矩阵
print(torch.zeros(2, 2, dtype=torch.long))

# 创建一个以1填充的矩阵
print(torch.ones(3, 3, dtype=torch.int32))

# 创建一个常量矩阵
print(torch.tensor([[1, 2, 3], [2, 3, 4]], dtype=torch.float64))

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 1.0928e-38, 9.9184e-39]])
tensor([[0.0140, 0.4002, 0.1155, 0.2961],
        [0.5432, 0.8869, 0.8256, 0.2656],
        [0.7899, 0.8192, 0.2751, 0.7749],
        [0.8417, 0.3961, 0.0172, 0.6831]])
tensor([[0, 0],
        [0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)


## 2.张量属性

In [8]:
test = torch.tensor([[1, 3, 5, 9], [2, 4, 6, 9], [0, 0, 0, 8], [6, 3, 1, 4]])
# 查看张量的大小
print(test.size())

# 创建新的张量 new_*
print(test.new_ones(5, 3))
print(test.new_zeros(3, 3))

# 按照test的形状创建新的张量
print(torch.randn_like(test, dtype=torch.float32))

torch.Size([4, 4])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[ 1.4248, -0.0763,  0.0507, -0.5932],
        [ 0.4968,  1.6596, -0.0353,  0.0362],
        [-0.7931, -1.3633,  0.8704, -1.9754],
        [-1.4445,  0.8753,  0.3584,  0.0626]])


## 3.张量运算
ps:任何以 _ 结尾的操作都会替换原有变量

In [3]:
# 加/减法
x = torch.rand(5, 3)
y = torch.rand(5, 3)

# 相加得到一个新的张量
print(x + y)
# 将一个张量加上另一个张量
y.add_(x)
print(y)

# 相加后作为新的参数输出
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[1.3641, 0.8083, 1.3879],
        [1.1251, 0.5018, 1.8244],
        [0.9540, 1.3249, 0.2458],
        [1.2688, 1.4487, 1.6471],
        [1.1975, 0.8152, 0.3261]])
tensor([[1.3641, 0.8083, 1.3879],
        [1.1251, 0.5018, 1.8244],
        [0.9540, 1.3249, 0.2458],
        [1.2688, 1.4487, 1.6471],
        [1.1975, 0.8152, 0.3261]])


tensor([[2.1596, 1.2221, 2.1759],
        [1.3019, 0.5799, 2.7439],
        [1.2216, 1.8024, 0.4018],
        [1.7407, 2.1139, 2.5912],
        [2.1350, 1.5550, 0.5432]])

In [11]:
# 按索引取数据，同numpy
print(test)

# view的用法
print(test.view(-1))   # 一维矩阵

# view与reshape类似
print(test.view(-1, 8))   # 二维矩阵, 没维中的元素数量为第二个参数的疏朗

# 一个元素的张量，可以使用item() 得到python数据类型的
t = torch.randn(1)
print(t.item())

tensor([[1, 3, 5, 9],
        [2, 4, 6, 9],
        [0, 0, 0, 8],
        [6, 3, 1, 4]])
tensor([1, 3, 5, 9, 2, 4, 6, 9, 0, 0, 0, 8, 6, 3, 1, 4])
tensor([[1, 3, 5, 9, 2, 4, 6, 9],
        [0, 0, 0, 8, 6, 3, 1, 4]])
-0.7175124287605286


## 4.numpy 转换

In [6]:
import numpy as np

In [7]:
# tensor转为 numpy
print(test.numpy())

# numpy 转为tensor
a = np.array([1, 2, 3], dtype=np.float64)
print(torch.from_numpy(a))

[[1 3 5]
 [2 4 6]
 [0 0 0]]
tensor([1., 2., 3.], dtype=torch.float64)


## 5.CUDA张量

In [8]:
# 判断是否有CUDA 可以用
if torch.cuda.is_available():
    pass

# 自动微分

## 1.跟踪所有对张量的操作

In [17]:
# 创建张量，并跟踪张量
x = torch.ones(3, 3, requires_grad=True)
print(x)

y = x + 2
print(y)
print(y.grad_fn)

# 对x进行操作
z = y * y * 3
out = z.mean()
print(z)
print(out)

# 对任意张量改变requires_grad属性
a = torch.ones(2, 2)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
False
True
tensor(4., grad_fn=<SumBackward0>)


## 2.梯度

In [18]:
# 因为out是一个标量，对out进行求导
print(out.backward())
print(x.grad)

None
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [24]:
# 向量可导
x = torch.randn(3, requires_grad=True)
print(x)
print(x.grad)

y = x * 2
while y.data.norm() < 1000:
    y *= 2

print(y)
# 此时y不再是个标量,将向量作为参数向后传递即可得到雅可比积
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([ 0.6700,  0.8001, -1.3855], requires_grad=True)
None
tensor([  686.0837,   819.2719, -1418.7572], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
